happybox-project/happybox

src/main/resources/static/css/admin/sidebar.css, src/main/resources/static/js/admin/sidebar.js, src/main/resources/templates/admin/sidebar.html
=> admin sidebar

src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/templates/admin/admin-boardList.html
=> admin boardList 추가

src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/static/css/admin/sidebar.css, src/main/resources/static/js/admin/checkbox.js, src/main/resources/static/js/admin/menuLoad.js, src/main/resources/static/js/admin/page.js, src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-inquiryList.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareList.html, src/main/resources/templates/admin/sidebar.html
admin member, notice, reply, welfare, inquiry, distributor List 추가
=> admin member, notice, reply, welfare, inquiry, distributor List 추가

src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/static/css/admin/admin-default.css, src/main/resources/static/css/admin/admin-modal.css, src/main/resources/static/css/admin/sidebar.css, src/main/resources/static/js/admin/modal.js, src/main/resources/templates/admin/admin-boardList.html, src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-inquiryList.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareList.html, src/main/resources/templates/admin/sidebar.html
delete modal, 회원 상세보기 modal 생성
=> delete modal, 회원 상세보기 modal 생성

src/main/resources/static/css/admin/admin-default.css, src/main/resources/static/css/admin/admin-detail.css, src/main/resources/static/css/admin/admin-modal.css, src/main/resources/static/js/admin/modal.js, src/main/resources/templates/admin/admin-boardList.html, src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-inquiryList.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareDetail.html, src/main/resources/templates/admin/admin-welfareList.html
member 상세 모달, welfareDetail page 추가
=> member 상세 모달, welfareDetail page 추가

src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/static/css/admin/admin-default.css, src/main/resources/static/css/admin/admin-detail.css, src/main/resources/static/css/admin/admin-modal.css, src/main/resources/static/js/admin/event.js, src/main/resources/templates/admin/admin-boardList.html, src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-inquiryDetail.html, src/main/resources/templates/admin/admin-inquiryList.html, src/main/resources/templates/admin/admin-inquiryModify.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareDetail.html, src/main/resources/templates/admin/admin-welfareList.html, src/main/resources/templates/admin/sidebar.html
inquiry detail, modify 생성, List modal 수정
=> inquiry detail, modify 생성, List modal 수정

src/main/resources/static/css/CS/common.css, src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/static/js/admin/event.js, src/main/resources/templates/admin/admin-boardList.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareDetail.html, src/main/resources/templates/admin/donate-detail.html
=> List 피드백 수정, donate detail 생성

src/main/resources/static/css/admin/admin-boardList.css, src/main/resources/static/css/admin/admin-detail.css, src/main/resources/static/css/admin/admin-modal.css, src/main/resources/static/css/admin/sidebar.css, src/main/resources/static/js/admin/event.js, src/main/resources/templates/admin/admin-boardList.html, src/main/resources/templates/admin/admin-distributorDetail.html, src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-inquiryDetail.html, src/main/resources/templates/admin/admin-inquiryModify.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-noticeList.html, src/main/resources/templates/admin/admin-replyList.html, src/main/resources/templates/admin/admin-welfareList.html, src/main/resources/templates/admin/sidebar.html
=> 피드백 반영사항 수정

src/main/java/com/app/happybox/config/QueryDslConfig.java, src/main/java/com/app/happybox/entity/board/ReviewBoard.java, src/main/java/com/app/happybox/entity/subscript/Subscription.java, src/main/java/com/app/happybox/entity/subscript/SubscriptionDTO.java, src/main/java/com/app/happybox/entity/type/SubOption.java, src/main/java/com/app/happybox/entity/user/Address.java, src/main/java/com/app/happybox/entity/user/Member.java, src/main/java/com/app/happybox/entity/user/User.java, src/main/java/com/app/happybox/entity/user/Welfare.java, src/main/java/com/app/happybox/repository/subscript/SubscriptionQueryDsl.java, src/main/java/com/app/happybox/repository/subscript/SubscriptionQueryDslImpl.java, src/main/java/com/app/happybox/repository/subscript/SubscriptionRepository.java, src/main/java/com/app/happybox/repository/user/DistributorQueryDsl.java, src/main/java/com/app/happybox/repository/user/DistributorQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/DistributorRepository.java, src/main/java/com/app/happybox/repository/user/MemberQueryDsl.java, src/main/java/com/app/happybox/repository/user/MemberQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/MemberRepository.java, src/main/java/com/app/happybox/repository/user/WelfareQueryDsl.java, src/main/java/com/app/happybox/repository/user/WelfareQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/WelfareRepository.java, src/main/resources/application.yml, src/main/resources/static/js/main/banner.js, src/test/java/com/app/happybox/repository/subscript/SubscriptionRepositoryTests.java, src/test/java/com/app/happybox/repository/user/MemberRepositoryTests.java, src/test/java/com/app/happybox/repository/user/WelfareRepositoryTests.java
subscription, member, welfare repository 생성
=> OneToOne N + 1 문제 단방향 적용, repository 생성

src/main/java/com/app/happybox/entity/customer/Inquiry.java, src/main/java/com/app/happybox/entity/customer/Notice.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerQueryDsl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerQueryDslImpl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryQueryDsl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryQueryDslImpl.java, src/main/java/com/app/happybox/repository/notice/NoticeQueryDsl.java, src/main/java/com/app/happybox/repository/notice/NoticeQueryDslImpl.java, src/main/java/com/app/happybox/repository/notice/NoticeRepository.java, src/test/java/com/app/happybox/repository/inquiry/InquiryAnswerRepositoryTests.java, src/test/java/com/app/happybox/repository/inquiry/InquiryRepositoryTests.java, src/test/java/com/app/happybox/repository/notice/NoticeRepositoryTests.java
=> 문의, 공지사항 레포지토리 작업

src/main/java/com/app/happybox/entity/customer/Inquiry.java, src/main/java/com/app/happybox/entity/customer/InquiryAnswer.java, src/main/java/com/app/happybox/entity/customer/Notice.java, src/main/java/com/app/happybox/entity/customer/NoticeDTO.java, src/main/java/com/app/happybox/entity/file/InquiryAnswerFile.java, src/main/java/com/app/happybox/entity/file/InquiryFile.java, src/main/java/com/app/happybox/entity/file/NoticeFile.java, src/main/java/com/app/happybox/entity/type/InquiryType.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerFileQueryDsl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerFileQueryDslImpl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerFileRepository.java, src/main/java/com/app/happybox/repository/inquiry/InquiryAnswerQueryDslImpl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryFileQueryDsl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryFileQueryDslImpl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryFileRepository.java, src/main/java/com/app/happybox/repository/inquiry/InquiryQueryDsl.java, src/main/java/com/app/happybox/repository/inquiry/InquiryQueryDslImpl.java, src/main/java/com/app/happybox/repository/notice/NoticeFileQueryDsl.java, src/main/java/com/app/happybox/repository/notice/NoticeFileQueryDslImpl.java, src/main/java/com/app/happybox/repository/notice/NoticeFileRepository.java, src/main/java/com/app/happybox/repository/notice/NoticeQueryDslImpl.java, src/test/java/com/app/happybox/repository/inquiry/InquiryAnswerRepositoryTests.java, src/test/java/com/app/happybox/repository/inquiry/InquiryRepositoryTests.java, src/test/java/com/app/happybox/repository/notice/NoticeRepositoryTests.java
inquiry, notice 레포지토리 file 추가 수정작업
=> inquiry, notice 레포지토리 file 추가 수정작업

src/main/java/com/app/happybox/controller/cs/CsController.java, src/main/java/com/app/happybox/domain/PageDTO.java, src/main/java/com/app/happybox/entity/customer/NoticeSearch.java, src/main/java/com/app/happybox/repository/notice/NoticeQueryDslImpl.java, src/main/resources/static/css/CS/common.css, src/main/resources/static/js/CS/list.js, src/main/resources/static/js/CS/notice-page.js, src/main/resources/static/js/CS/search.js, src/main/resources/templates/CS/notice.html, src/main/resources/templates/CS/sidebar.html
공지사항 목록 controller 및 화면 처리, 검색, paging 처리 작성
=> 공지사항 목록 controller 및 화면 처리, 검색, paging 처리 작성

src/main/resources/static/js/CS/common.js, src/main/resources/static/js/CS/detail.js, src/main/resources/static/js/CS/list.js, src/main/resources/templates/CS/notice-detail.html, src/main/resources/templates/CS/notice.html
=> notice  date 값 변경

src/main/java/com/app/happybox/controller/admin/AdminController.java, src/main/java/com/app/happybox/repository/notice/NoticeQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/MemberQueryDsl.java, src/main/java/com/app/happybox/repository/user/MemberQueryDslImpl.java, src/main/java/com/app/happybox/service/cs/NoticeService.java, src/main/java/com/app/happybox/service/cs/NoticeServiceImpl.java, src/main/java/com/app/happybox/service/user/MemberService.java, src/main/java/com/app/happybox/service/user/MemberServiceImpl.java, src/main/resources/static/js/admin/admin-notice.js, src/main/resources/templates/admin/admin-noticeList.html
commit 안하고 계속 풀만 받았더니 요래 됐네요.;;;
=> 비밀번호 찾기 추가, admin notice 컨트롤러에 작성

src/main/java/com/app/happybox/controller/admin/AdminController.java, src/main/resources/static/js/admin/admin-notice.js
=> rest 페이징 처리

src/main/java/com/app/happybox/config/SecurityConfig.java, src/main/java/com/app/happybox/controller/admin/AdminController.java, src/main/java/com/app/happybox/entity/customer/Notice.java, src/main/java/com/app/happybox/entity/file/NoticeFile.java, src/main/java/com/app/happybox/service/cs/NoticeService.java, src/main/java/com/app/happybox/service/cs/NoticeServiceImpl.java, src/main/resources/application.yml, src/main/resources/static/js/admin/admin-notice.js, src/main/resources/static/js/admin/event.js, src/main/resources/templates/admin/admin-noticeList.html
=> 공지사항 작성 완료 파일 업로드 가능

build.gradle, src/main/java/com/app/happybox/config/MailConfig.java, src/main/java/com/app/happybox/controller/user/MemberController.java, src/main/java/com/app/happybox/controller/user/UserRestController.java, src/main/java/com/app/happybox/domain/user/MailDTO.java, src/main/java/com/app/happybox/entity/user/User.java, src/main/java/com/app/happybox/entity/user/UserRandomKey.java, src/main/java/com/app/happybox/repository/user/RandomKeyQueryDsl.java, src/main/java/com/app/happybox/repository/user/RandomKeyQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/RandomKeyRepository.java, src/main/java/com/app/happybox/repository/user/UserQueryDsl.java, src/main/java/com/app/happybox/repository/user/UserQueryDslImpl.java, src/main/java/com/app/happybox/repository/user/UserRepository.java, src/main/java/com/app/happybox/service/user/RandomKeyService.java, src/main/java/com/app/happybox/service/user/RandomKeyServiceImpl.java, src/main/java/com/app/happybox/service/user/UserService.java, src/main/java/com/app/happybox/service/user/UserServiceImpl.java, src/main/resources/application.yml, src/main/resources/static/css/member/change-password.css, src/main/resources/static/css/member/confirm-id.css, src/main/resources/static/js/join/change-password.js, src/main/resources/static/js/join/find.js, src/main/resources/templates/member/change-password.html, src/main/resources/templates/member/find-id.html, src/main/resources/templates/member/find-pw.html, src/main/resources/templates/member/member-login.html
=> 회원 아이디 찾기, 비밀번호 찾기 완성

src/main/java/com/app/happybox/controller/cs/CsController.java, src/main/java/com/app/happybox/controller/main/WelfareMainController.java, src/main/java/com/app/happybox/service/cs/InquiryService.java, src/main/java/com/app/happybox/service/cs/InquiryServiceImpl.java, src/main/resources/static/css/CS/write-inquiry.css, src/main/resources/templates/CS/notice-detail.html, src/main/resources/templates/CS/notice.html, src/main/resources/templates/CS/sidebar.html, src/main/resources/templates/CS/write-inquiry.html, src/main/resources/templates/component/header.html
고객센터 header, footer 붙이기 및 공공API 불러오기
=> 고객센터 header, footer 붙이기 및 공공API 불러오기

src/main/resources/static/css/CS/common.css, src/main/resources/static/css/welfare/donateInsert.css, src/main/resources/static/js/member/donate-insert.js, src/main/resources/templates/user-board/donate-insert.html
=> donate board 공공데이터 불러오기

src/main/resources/static/css/member/modal.css, src/main/resources/static/js/CS/use-info.js, src/main/resources/templates/CS/faq.html, src/main/resources/templates/member/welfare-join.html
=> 복지관 회원가입 api 불러오기 및 faq 작성

src/main/java/com/app/happybox/controller/cs/CsController.java, src/main/resources/static/css/member/confirm-id.css, src/main/resources/static/js/CS/detail.js, src/main/resources/static/js/join/change-password.js, src/main/resources/static/js/join/find.js, src/main/resources/templates/CS/sidebar.html, src/main/resources/templates/member/find-id.html, src/main/resources/templates/member/find-pw.html
=> 링크 수정 및 모달 추가

src/main/java/com/app/happybox/controller/cs/CsController.java, src/main/resources/templates/CS/sidebar.html
=> 문의 작성 링크 수정

src/main/java/com/app/happybox/controller/user/OAuthController.java, src/main/java/com/app/happybox/domain/user/OAuthAttributes.java, src/main/java/com/app/happybox/provider/UserDetail.java, src/main/java/com/app/happybox/service/user/MemberOAuthService.java
OAuth로 회원가입 및 OAuth 로그인 시 userDetail에 값 담아주기
=> OAuth로 회원가입 및 OAuth 로그인 시 userDetail에 값 담아주기

src/main/resources/static/css/admin/admin-modal.css, src/main/resources/static/js/admin/admin-notice.js, src/main/resources/templates/member/change-password.html, src/main/resources/templates/user-board/review-board-insert.html
=> 복지관 공공데이터 및 기타 css 수정

src/main/resources/templates/admin/admin-distributorList.html, src/main/resources/templates/admin/admin-donateBoardList.html, src/main/resources/templates/admin/admin-memberList.html, src/main/resources/templates/admin/admin-recipeBoardList.html, src/main/resources/templates/admin/admin-reviewBoardList.html, src/main/resources/templates/admin/admin-welfareList.html
=> 관리자 페이지 버튼 레이아웃 숨기기

src/main/java/com/app/happybox/service/user/MemberServiceImpl.java
=> 문자 날리기 활성화
